-- This file is intentionally minimal. The authoritative database
-- schema for Orion-v1 is maintained in the migration scripts under:
--
--    supabase/migrations/0001_init.sql
--
-- The migration contains all table definitions, indexes, triggers, RLS
-- policies and other database constructs required by the application.
-- Keep this file as a pointer or remove it once the migration mechanism is
-- in place.
